

Create table CLIENTES (
	CLI_CEDULA numeric(10,0) NOT NULL ,
	CLI_NOMBRE varchar (30) NOT NULL ,
	CLI_DIRECCION varchar (30) NOT NULL ,
	CLI_TELEFONO varchar (30) NOT NULL 
) 
;

ALTER TABLE CLIENTES ADD CONSTRAINT CLI_CEDULA PRIMARY KEY (CLI_CEDULA)
;

Create table MASCOTAS (
	MAS_CODIGO numeric(10,0) NOT NULL ,
	CLI_CEDULA numeric(10,0) NOT NULL ,
	MAS_NOMBRE varchar (30) NOT NULL ,
	MAS_EDAD numeric(10,0) NOT NULL 
) 
;

ALTER TABLE MASCOTAS ADD CONSTRAINT MAS_CODIGO PRIMARY KEY (MAS_CODIGO)
;

Create table VACUNAS (
	VAC_CODIGO numeric(10,0) NOT NULL ,
	VAC_NOMBRE varchar (50) NOT NULL 
) 
;

ALTER TABLE VACUNAS ADD CONSTRAINT VAC_CODIGO PRIMARY KEY (VAC_CODIGO)
;

Create table VACUNAS_MASCOTAS (
	MAS_CODIGO numeric(10,0) NOT NULL ,
	VAC_CODIGO numeric(10,0) NOT NULL ,
	VACMAS_FECHA Date NOT NULL
) 
;

ALTER TABLE VACUNAS_MASCOTAS ADD CONSTRAINT MAS_VAC_CODIGO PRIMARY KEY (MAS_CODIGO, VAC_CODIGO)
;

ALTER TABLE MASCOTAS ADD CONSTRAINT CEDULA_DUENO FOREIGN KEY (CLI_CEDULA) REFERENCES CLIENTES (CLI_CEDULA)
;

ALTER TABLE VACUNAS_MASCOTAS ADD CONSTRAINT VACUNA_MASCOTA FOREIGN KEY (MAS_CODIGO) REFERENCES MASCOTAS (MAS_CODIGO)
;

ALTER TABLE VACUNAS_MASCOTAS ADD CONSTRAINT CODIGO_VACUNA FOREIGN KEY (VAC_CODIGO) REFERENCES VACUNAS (VAC_CODIGO)
;


